# Generated by Django 2.2.16 on 2022-07-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220701_1035'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_constraint',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='title_author_unique'),
        ),
    ]
